DROP DATABASE IF EXISTS IPAPI;
DROP TABLE IF EXISTS beer;

CREATE DATABASE IPAPI;

CREATE TABLE beer (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    beer_name VARCHAR(30) UNIQUE NOT NULL,
    brewery VARCHAR(30) NOT NULL,
    beer_type VARCHAR(30) NOT NULL

)