INSERT INTO beer (beer_name, brewery, beer_type)
VALUES
('Breakfast Stout', 'Founders Brewing', 'Stout'),
('90 Minute IPA', 'Dogfish Head', 'IPA'),
('Two Hearted Pale', 'Bells Brewery', 'IPA'),
('Pliny the Elder', 'Russian River Brewing', 'IPA'),
('Heady Topper', 'The Alchemist', 'IPA'),
('Sculpin', 'Ballast Point Brewing', 'IPA'),
('KBS', 'Founders Brewing', 'Stout'),
('Hopslam Ale', 'Bells Brewery', 'IPA'),
('Old Rasputin', 'North Coast Brewing', 'Stout'),
('60 Minute IPA', 'Dogfish Head', 'IPA'),
('Pale Ale', 'Sierra Nevada', 'Pale Ale'),
('Stone IPA', 'Stone Brewing', 'IPA'),
('Torpedo Extra IPA', 'Sierra Nevada', 'IPA'),
('Zombie Dust', '3 Floyds Brewing Co.', 'Pale Ale'),
('Enjoy By IPA', 'Stone Brewing', 'IPA'),
('Arrogant Bastard Ale', 'Arrogant', 'IPA'),
('Celebration', 'Sierra Nevada', 'IPA'),
('Lagunitas', 'Lagunitas ', 'IPA'),
('Ten Fidy', 'Oskar Blues', 'Stout'),
('Boston Lager', 'Samuel Adams', 'Lager'),
('Little Sumpin', 'Lagunitas', 'IPA'),
('Fat Tire Amber', 'New Belgium', 'Amber'),
('Guinness', 'Guinness', 'Stout'),
('Samuel Adams Octoberfest', 'Samuel Adams', 'Lager'),
('Dales Pale', 'Oskar Blues', 'Pale Ale'),
('Double Jack', 'Firestone Walker', 'IPA'),
('Hop Devil', 'Victory Brewing', 'IPA'),
('The Abyss', 'Deschutes Brewery', 'Stout'),
('Parabola', 'Firestone Walker', 'Stout'),
('Lager', 'Yuenglings Brewery', 'Lager'),
('Alpha King', '3 Floyds Brewing', 'Stout'),
('Budweiser', 'Anheuser-Busch', 'Lager'),
('Bud Light', 'Anheuser-Busch', 'Lager'),
('Anchor Steam', 'Anchor Steam', 'Lager'),
('Stella Artois', 'Stella Artois', 'Lager'),
('Goose IPA', 'Goose Island', 'IPA'),
('Coors Light', 'Coors', 'Lager'),
('Corona', 'Corona', 'Lager'),
('Miller Light', 'Miller', 'Lager'),
('Miller High Life', 'Miller', 'Lager'),
('Obsidian Stout', 'Deschutes', 'Stout'),
('420 Extra Pale Ale', 'SweetWater Brewing', 'Pale'),
('Mirror Pond Ale', 'Deschutes', 'Pale Ale');
